import 'dart:developer';
import 'package:firebase_core/firebase_core.dart';
import '../../firebase_options.dart';

// This file expects `firebase_options.dart` generated by FlutterFire CLI.
// Run: flutter pub add flutterfire_cli ; dart run flutterfire_cli
// Then `flutterfire configure` to create `lib/firebase_options.dart`.
// We guard initialization when options are missing to avoid blank screen in web.

class FirebaseService {
  static bool _initialized = false;

  static Future<void> init() async {
    if (_initialized) return;
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      _initialized = true;
      log('Firebase initialized');
    } catch (e, st) {
      log('Firebase init skipped or failed: $e', stackTrace: st);
      // Continue app without Firebase; after configuration, this will succeed.
    }
  }
}
